name: Patriot Cruises
favicon: null
layout_spectrum: 0.48447
typography_spectrum: 0.10290856030769646
title: Patriot Cruises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#004f93'
    - '#c5253e'
    - '#679ed1'
    - '#d07b88'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
